name: Makefile CI

jobs:
  macos-arm:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install meson texinfo
    - name: Compile
      run: make NPROC=4 TARGET=arm-none-eabi PREFIX=/var/tmp/build build_all
    - name: Package
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccarm-macos_aarch64.zip"
        directory: "/var/tmp/build/"
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccarm-macos_aarch64.zip"
        artifactContentType: "application/zip"
        tag: "gcc-arm-macos_aarch64-13.2.0-1"
        commit: "main"
        allowUpdates: true
