name: macOS crossbuild

on:
  workflow_dispatch:
    inputs:
      target:
        description: Target
        default: arm-none-eabi
        type: choice
        options:
          - arm-none-eabi
          - msp430-elf
          - avr
      release:
        description: Release
        default: 13.2.0-1
        type: string

jobs:
  crossbuild:
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install meson texinfo
    - name: Compile
      run: make NPROC=4 TARGET=${{ inputs.target }} PREFIX=/var/tmp/build build_all
    - name: Package
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        filename: /var/tmp/toolchain-gcc${{ inputs.target }}-macos_aarch64.zip"
        directory: /var/tmp/build/
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: /var/tmp/toolchain-gcc${{ inputs.target }}-macos_aarch64.zip
        artifactContentType: application/zip
        tag: gcc-${{ inputs.target }}-macos_aarch64-${{ inputs.release }}
        commit: main
        allowUpdates: true
