name: Makefile CI

env:
  VERSION: 13.2.0-1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Meson
      run: sudo apt-get install -y meson
    - name: Compile AVR
      run: make NPROC=4 TARGET=avr PREFIX=/var/tmp/avr build_all
    - name: Compile ARM
      run: make NPROC=4 TARGET=arm-none-eabi PREFIX=/var/tmp/arm-none-eabi build_all
    - name: Compile MSP430
      run: make NPROC=4 TARGET=msp430-elf PREFIX=/var/tmp/msp430-elf build_all
    - name: Package ARM
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccarm-linux.zip"
        directory: "/var/tmp/arm-none-eabi/"
    - name: Package AVR
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccavr-linux.zip"
        directory: "/var/tmp/avr/"
    - name: Package MSP430
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccmsp430-linux.zip"
        directory: "/var/tmp/msp430-elf/"
    - name: Release ARM
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccarm-linux.zip"
        artifactContentType: "application/zip"
        tag: "gcc-arm-linux-13.2.0-1"
        commit: "main"
        allowUpdates: true
    - name: Release AVR
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccavr-linux.zip"
        artifactContentType: "application/zip"
        tag: "gcc-avr-linux-13.2.0-1"
        commit: "main"
        allowUpdates: true
    - name: Release MSP430
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccmsp430-linux.zip"
        artifactContentType: "application/zip"
        tag: "gcc-msp430-linux-13.2.0-1"
        commit: "main"
        allowUpdates: true

  macos-aarch64:
    if: false
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install meson texinfo
    - name: Compile ARM
      run: make NPROC=4 TARGET=arm-none-eabi PREFIX=/var/tmp/arm-none-eabi build_all
    - name: Compile AVR
      run: make NPROC=4 TARGET=avr PREFIX=/var/tmp/avr build_all
    - name: Compile MSP430
      run: make NPROC=4 TARGET=msp430-elf PREFIX=/var/tmp/msp430-elf build_all
    - name: Package ARM
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccarm-macos-aarch64.zip"
        directory: "/var/tmp/arm-none-eabi/"
    - name: Package AVR
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccavr-macos-aarch64.zip"
        directory: "/var/tmp/avr/"
    - name: Package MSP430
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "zip"
        filename: "/var/tmp/toolchain-gccmsp430-macos-aarch64.zip"
        directory: "/var/tmp/msp430-elf/"
    - name: Release ARM
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccarm-macos-aarch64.zip"
        artifactContentType: "application/zip"
        tag: "gcc-arm-macos-aarch64-13.2.0-1"
        commit: "main"
        allowUpdates: true
    - name: Release AVR
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccavr-macos-aarch64.zip"
        artifactContentType: "application/zip"
        tag: "gcc-avr-macos-aarch64-13.2.0-1"
        commit: "main"
        allowUpdates: true
    - name: Release MSP430
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/var/tmp/toolchain-gccmsp430-macos-aarch64.zip"
        artifactContentType: "application/zip"
        tag: "gcc-msp430-macos-aarch64-13.2.0-1"
        commit: "main"
        allowUpdates: true
