name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Meson
      run: sudo apt-get install -y meson
    - name: Compile
      run: make NPROC=4 TARGET=arm-none-eabi build_all
